### PR TITLE
Fix keyboard navigation after category change, fixes #402

### LINKED ISSUE #402: Incorrect keyboard navigation from categories to the emoji list
When navigating with the arrow key down from the categories row to the emoji list focus jumps to the second visible row instead of the first one (note: "Recently Used" category should not be empty to reproduce the issue).

How to reproduce the issue:
1) Select a few emojis to push some to the "Recently used" category
2) Switch between categories
3) Use the arrow key down to change focus from a category button to the emoji list

Was reproduced on chrome v122, macOs 13.4.1 

https://github.com/ealush/emoji-picker-react/assets/64484706/04604d9d-0441-4a66-8db7-d5c001f484de

### PR DESCRIPTION
**Pull request by thiltunen**
Resolves https://github.com/ealush/emoji-picker-react/issues/402

### CODE REVIEW

File: src/DomUtils/elementPositionInRow.ts [hunk 1]
```diff
@@ -143,28 +143,36 @@ export function getElementInPrevRow(
...
     }
 
     return (
-      (elementTop >= parentTop && elementTop <= parentBottom) ||
-      (elementBottom >= parentTop && elementBottom <= parentBottom)
+      (elementTopWithAllowedDiff >= parentTop &&
+        elementTopWithAllowedDiff <= parentBottom) ||
+      (elementBottomWithAllowedDiff >= parentTop &&
+        elementBottomWithAllowedDiff <= parentBottom)
     );
```
Comment (thiltunen) [inline src/DomUtils/elementPositionInRow.ts:176]: after fixing `getLabelHeight` logic, the remaining issue was that this check didn't pass because of the 1px difference caused by the `scrollTo` function, i wasn't sure why this 1px offset was added `$eprBody.scrollTop = top + 1;` so instead of removing it (fixes the issue as well) i thought it's a good idea to introduce an optional threshold for visibility calculations

export function scrollTo(root: NullableElement, top: number = 0) {
  const $eprBody = queryScrollBody(root);

  if (!$eprBody) {
    return;
  }

  requestAnimationFrame(() => {
    $eprBody.scrollTop = top + 1;
  });
}

File: src/DomUtils/elementPositionInRow.ts [hunk 2]
```diff
@@ -175,10 +183,18 @@ export function hasNextElementSibling(element: HTMLElement) {
...
 }
 
-function getLabelHight(parentNode: HTMLElement) {
-  return (
-    parentNode
-      .querySelector(asSelectors(ClassNames.label))
-      ?.getBoundingClientRect().height ?? DEFAULT_LABEL_HEIGHT /* default */
+function getLabelHeight(parentNode: HTMLElement) {
+  const labels = Array.from(
+    parentNode.querySelectorAll(asSelectors(ClassNames.label))
```
[the remark this answers is not in the document]
Comment (ealush) [reply src/DomUtils/elementPositionInRow.ts:188]: OOh. Good point. Didn't think of that one.

File: src/DomUtils/elementPositionInRow.ts (hunk 1 above)
Comment (ealush) [reply src/DomUtils/elementPositionInRow.ts:176]: That's a good point. One thing, I just checked, and the reason that I needed that 1px is no longer relevant. Back then it messed up my active category calculation. Seems like it works well without it. I'll remove it soon enough :)

**Review by ealush — APPROVED** [review]
Thank you for this, @thiltunen Also, sorry for taking this long. I have been traveling the past couple of weeks. Will be merged and published shortly.
